name: Execute batch job at every 6:00 AM asia/tokyo
on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  batch:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
      VITE_SUPABASE_KEY: ${{secrets.VITE_SUPABASE_KEY}}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Execute batch
        run: npx tsx -r dotenv/config ./batch/index.ts
